version: "3"

x-defaults-db: &x-default-db
  # 이미지 지정 - Official Images로 컨테이너를 생성
  platform: linux/x86_64
  image: mysql:8
  command:
    - --default-authentication-plugin=mysql_native_password
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    - --lower_case_table_names=1
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: 1234qwer
    MYSQL_DATABASE: wantedlab

services:
  db:
    <<: *x-default-db
    container_name: db
    # 호스트에 있는 폴더를 컨테이너 안에 있는 폴더로 마운트
    volumes:
      - ./data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    # 연결 포트 지정
    ports:
      - "3306:3306"
  app:
    container_name: app
    environment:
      NODE_ENV: development
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
